sudo: false
language: node_js
cache:
  - bundler
node_js:
  - "5"
  - "4"
  - "0.12"
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - rvm use 2.2.2 --install --fuzzy
  - bundle install
matrix:
  fast_finish: true
notifications:
  email: false
  slack:
    secure: P/ngpvqinM/t9tdXZO2qHQvq2XCkcerKM+KwNJlQoVHnkl/Z/EtzB1yxiZZ6LGdHp+r3nShBhfW+gJVojU80EObt0iWHbFTkUUMFf6WI6c056937CksQI4atmDBiCJxMAnkd6DCLWfBexVtKDhkc5vX0bYhgoiXEzCYUhFd8pZ4=
